import Foundation

struct ExifLogEntry: Codable {
  let schemaVersion: Int?
  let pixcaptureVersion: String?
  let pixcaptureBuild: String?
  let levelCoordinateSystem: String?
  let rawPixelFormatType: UInt32?
  let rawPixelFormatFourCC: String?
  let rawCaptureKind: String?
  let previewRawDecoderVersion: String?
  let fileName: String
  let sequenceNumber: Int?
  let zone: String?
  let frameCount: Int?
  let requestedBiasEV: Double
  let requestedAspectRatio: Double
  let requestedExposureEV: Double
  let exposureEV: Double
  let requestedSeconds: Double
  let perFrameSeconds: Double?
  let effectiveSeconds: Double?
  let requestedISO: Float
  let activeFormatMinISO: Float?
  let activeFormatMaxISO: Float?
  let activeFormatMinExposureSeconds: Double?
  let activeFormatMaxExposureSeconds: Double?
  let seriesInitialBaseISO: Float?
  let seriesFinalBaseISO: Float?
  let seriesUsedRecoveryISO: Bool?
  let deviceExposureSeconds: Double?
  let deviceISO: Float?
  let deviceExposureTargetBias: Float?
  let deviceExposureTargetOffset: Float?
  let deviceLensPosition: Float?
  let deviceFocusMode: String?
  let deviceFocusPointX: Double?
  let deviceFocusPointY: Double?
  let deviceAdjustingFocus: Bool?
  let deviceSubjectAreaMonitoringEnabled: Bool?
  let deviceZoomFactor: Double?
  let deviceWhiteBalanceGainRed: Float?
  let deviceWhiteBalanceGainGreen: Float?
  let deviceWhiteBalanceGainBlue: Float?
  let exifExposureTime: Double?
  let exifExposureBiasValue: Double?
  let exifBrightnessValue: Double?
  let meanLuma: Double?
  let exifExposureProgram: Int?
  let exifMeteringMode: Int?
  let exifISO: Double?
  let fNumber: Double?
  let focalLength: Double?
  let lensModel: String?
  let exifPixelXDimension: Int?
  let exifPixelYDimension: Int?
  let pixelWidth: Int?
  let pixelHeight: Int?
  let depthDeliverySupported: Bool?
  let depthDeliveryEnabled: Bool?
  let streamDepthSupported: Bool?
  let streamDepthEnabled: Bool?
  let depthReferenceFrame: Bool?
  let depthDataPresent: Bool?
  let depthSidecarWritten: Bool?
  let depthSource: String?
  let depthAggregation: String?
  let depthDataType: String?
  let depthMapWidth: Int?
  let depthMapHeight: Int?
  let depthDataFiltered: Bool?
  let depthDataAccuracy: String?
  let depthDataQuality: String?
  let depthCalibrationPresent: Bool?
  let orientation: Int?
  let resolvedMetadataOrientation: Int?
  let requestedCaptureOrientation: String?
  let connectionRotationAngle: Double?
  let make: String?
  let model: String?
  let software: String?
  let whiteBalance: Int?
  let dateTimeOriginal: String?
  let histogramBins: [Double]?
  let exposureQualityState: String?
  let sharpnessQualityState: String?
  let warningMessageSnapshot: String?
  let levelAngleDegrees: Double?
  let levelPitchDegrees: Double?
  let singleShotTriggeredAt: String?
  let singleShotRollDegrees: Double?
  let singleShotPitchDegrees: Double?
  let singleShotStabilityScore: Double?
  let singleShotStabilityState: String?
  let singleShotCorrectability: String?
  let intendedProcessing: String?
}
